
# **Is your feature request related to a problem? Please describe.**
# A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

# **Describe the solution you'd like**
# A clear and concise description of what you want to happen.

# **Describe alternatives you've considered**
# A clear and concise description of any alternative solutions or features you've considered.

# **Additional context**
# Add any other context or screenshots about the feature request here.

name: Feature Request
description: Suggest an idea 💡
title: "[Feat]: "
labels: ["🤩 New Feature"]
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-do-you-want
    attributes:
      label: What do you want? 🤔
      description: Also tell us, what did you expect to happen?
      placeholder: A bug happened!
      # value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: what-should-it-look-like
    attributes:
      label: What should it look like? 🤦‍♀️
      description: Also tell us, what did you expect to happen?
      placeholder: Hummm, it should be ...
      # value: "Hummm, it should be ..."
    validations:
      required: false
      
  - type: textarea
    id: how-to-test-reproduce
    attributes:
      label: How to test / reproduce? 🧪
      # description: Also tell us, what did you expect to happen?
      placeholder: Open the refrigerator, take out the giraffe, put in the elephant and close the door.
      # value: "Hummm, it should be ..."
    validations:
      required: false
  - type: textarea
    id: any-suggestions-that-may-help
    attributes:
      label: Any suggestions that may help? 😇
      description: Any suggestions, solutions or thoughts?
      placeholder: Did you try flex tape?
      # value: "Hummm, it should be ..."
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers you using the most?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - IE
  - type: checkbox
    id: contribute
    attributes:
      label: Would you like to help ous implementing this feature?
