name: get the Branch

on:
  push:
    branches:
      - main
      - dev
      - feature/*


jobs:
  set_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Get Pushed Branch
        id: get_branch
        uses: .github/actions/get-branch-name.yml

      - name: Use Branch Name
        run: |
          echo "Branch Name: ${{ steps.get_branch.outputs.branch }}"